### ISSUE TITLE
Retours

### ISSUE THREAD

**Issue by Rossb0b** [Batsave/Xmass-Click#32]
👋 , first of all ggs

UI :

It's not fully responsive, on very wild screens, the footer is in part visible but it's easy to see that's not wanted.

![image](https://github.com/Batsave/Xmass-Click/assets/39910164/1b50a3bf-fca5-480a-b273-7b0d9321733e)

It's nice having text that fully appears or not at all :)

UX  :

![image](https://github.com/Batsave/Xmass-Click/assets/39910164/46f6c61f-28a3-4d5d-927c-84e9e5ee44d9)

It's just nice having an effect on active links. Like if you are in the "Boutique", it should be highlighted somehow.

Game Design :

Actually, the game is playable from any page of the site through the coin holder.

![image](https://github.com/Batsave/Xmass-Click/assets/39910164/78a9618f-c5d9-45f7-9f95-d7d28aa9d8f6)

It makes the page "Jeu" a little bit useless.

**Comment by Tetardtek** [comment]
Thank you for checking our work and taking time to give us feedback!
First of all, I agree with most of what you said! :)
Obviously we working on it right now!

Stay tuned !

**Comment by Tetardtek** [comment]
Hey! 
Everything's done without the store problem; but we're going to rework it, so it'll be done then.

**Comment by Tetardtek** [comment]
Hey!
Everything's done without the store problem; but we're going to rework it, so it'll be done then.
